version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
      - "15674:15674"
      - "15675:15675"

  msql_db:
    image: mysql:8
    container_name: msql_db
    restart: always
    volumes:
      - mysql_db_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: web
      MYSQL_ROOT_PASSWORD: eee333rr
      MYSQL_USER: root
    ports:
      - "3307:3306"

volumes:
  mysql_db_volume:
